name = "hallucinating-splines"
main = "src/index.ts"
compatibility_date = "2026-01-16"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "hallucinating-splines-db"
database_id = "16f4c004-8985-42ed-aa81-369ee29bb15a"

[durable_objects]
bindings = [
  { name = "CITY", class_name = "CityDO" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["CityDO"]

[[migrations]]
tag = "v2"

[[r2_buckets]]
binding = "SNAPSHOTS"
bucket_name = "hallucinating-splines-snapshots"

[triggers]
crons = ["0 0 * * *"]
